BerkeleyHCI/PolymorphicBlocks

- edg_core/edgir/common_pb2.py
- edg_core/edgir/common_pb2.pyi
- edg_core/edgir/elem_pb2.py
- edg_core/edgir/elem_pb2.pyi
- edgir/common.proto
- edgir/elem.proto
Will re-generate the Python bindings before merging.
Partial fix (definitions only, implementation to come later) for #9
> Define message structs for currently used metadata defs

- compiler/src/main/scala/edg/compiler/ConstProp.scala
- compiler/src/main/scala/edg/compiler/ExprEvaluate.scala
- compiler/src/main/scala/edg/compiler/ExprToString.scala
- compiler/src/main/scala/edg/compiler/ExprValue.scala
- compiler/src/test/scala/edg/compiler/ExprEvaluateTest.scala
- edg_core/Array.py
- edg_core/ConstraintExpr.py
- edg_core/edgir/common_pb2.py
- edg_core/edgir/elem_pb2.py
- edg_core/edgir/expr_pb2.py
- edg_core/edgir/expr_pb2.pyi
- edg_core/edgir/impl_pb2.py
- edg_core/edgir/init_pb2.py
- edg_core/edgir/lit_pb2.py
- edg_core/edgir/name_pb2.py
- edg_core/edgir/ref_pb2.py
- edg_core/edgir/schema_pb2.py
- edg_core/edgir/type_pb2.py
- edgir/expr.proto
- electronics_model/DigitalPorts.py
- Add the hull reduction operator as the proper replacement for removing the min reduction operator on arrays of ranges, for calculating the superset link voltage given a set of bidirectional ports (and the optional source or sink port)
- Undefine (should error out) the min / max reduction on arrays of ranges - no longer used
- Undefine the min / max on empty array - no longer used
- Adds a hull binary operator (primarily because we don't have an array construction primitive - perhaps another refactor for another day)
- Add a proper concept of empty ranges (empty set equivalent for intervals) internal to the compiler
- Split RangeValue into RangeType, RangeValue(min, max) and RangeEmpty
- Hulling an empty array returns the empty range
- Intersecting an empty array returns the full set - …
> Add hull operator, remove min(array[range]) -> float

- compiler/src/main/scala/edg/wir/DesignPath.scala
- edg_core/NotConnectablePort.py
- edg_core/__init__.py
- electronics_lib/Lcd_Qt096t_if09.py
- electronics_lib/Microcontroller_Lpc1549.py
- electronics_lib/Microcontroller_Nucleo32.py
- electronics_lib/Microcontroller_Stm32f103.py
- electronics_model/DigitalPorts.py
- electronics_model/PinAssignmentUtil.py
DO NOT MERGE - DEPENDS ON #40, #43
Resolves #31, the two failing tests with the LCDs are now green. (Simon is still failing)
- Adds a `NotConnectablePort` mixin for `Port`, which adds the `not_connected()` function. This generates a dummy block (defined with the mixin) that defines a nop port for the port type, and connects the port there.
- This is mainly (only?) intended to be used where there are unused bundle components - here, MISO is not used for the LCD
- `not_connected()` is used to mark an edge port as disconnected, from the inside.
- This differs from schematic capture, which marks pins not-connected from the outside. That functionality is handled by the required port infrastructure, and there is no way to NC a port from the outside. However, schematics have no concept of …
> Add not-connected port support, fix (most) red tests

- edg_core/edgir/__init__.py
Allow namespace_order to handle the empty case (for which it returns an empty list), upper layers should crash if needed (for example, if there is a length mismatch between ordering).
Longer term: maybe eliminate the (unordered) map in the proto def so we don't need a supplemental order data structure?
> Don't crash on empty designs

- edg_core/Binding.py
- edg_core/ConstraintExpr.py
- edg_core/HdlInterfaceServer.py
- edg_core/HierarchyBlock.py
- edg_core/Range.py
- edg_core/__init__.py
- edg_core/edgir/__init__.py
- edg_core/test_block.py
- edg_core/test_generator.py
- edg_core/test_range.py
- edg_core/test_simple_const_prop.py
- edg_core/test_simple_expr_eval.py
- electronics_abstract_parts/AbstractPowerConverters.py
- electronics_abstract_parts/PassiveFilters.py
- electronics_abstract_parts/ResistiveDivider.py
- electronics_abstract_parts/test_resistive_divider.py
- electronics_lib/Crystals.py
- electronics_lib/DcDcConverters.py
- electronics_lib/Diodes.py
- electronics_lib/Fets.py
- electronics_lib/LinearRegulators.py
- electronics_lib/Passives.py
- electronics_lib/ProductTableUtils.py
- electronics_lib/test_preferred_number.py
- electronics_model/NetlistGenerator.py
- electronics_model/Units.py
- electronics_model/test_analog_link.py
- examples/test_battery_protector.py
Adds a Range type, for interval arithmetic, and including unit tests. Core definition is in Range.py, and refactors the code that uses tuples to use this. It's really mostly refactoring 🤪...
Additionally modifies the power converters dutycycle limits to be a constraint (instead of an assertion) so a design still generates, and a user may waive the constraint if it's fine for the converter to go into tracking mode. Fixes the battery protector example by removing the voltage-sensitive MCU and upping the output to 5V - previously it would have tracked up to the battery voltage of 4.2 and probably blew up the micro.
Prerequisite for #59, to replace the hacktastic old parts table adhoc range constructors.
TODO:
> Range type

- edg_core/ScalaCompilerInterface.py
It will default to the development JAR if that's present though.
> Add precompiled JAR so things work out of the box

- examples/test_tofarray/firmware/main.cpp
- examples/test_tofarray/firmware/platformio.ini
Adds the required firmware library for the VL53L0X to the PlatformIO config.
For some reason this didn't make it into #122, but since this is part of that I'm just going to go ahead and merge it.
> ToF array firmware PIO config fix

- HdlInterfaceService.py
- compiler/src/main/scala/edg/compiler/PythonInterface.scala
- Gets rid of the print-to-stderr that was getting ignored anyways and the verbose mode we don't use
- Error cases in HdlInterfaceServer will actually error out now
- The PythonInterface in Scala checks for dead subprocess and throws an appropriate error (including stderr from the dead subprocess), to differentiate from other failures
This turns out to be a significant quality-of-life improvement so I'm just going to merge this, but feedback is welcome and can be addressed in a follow-on PR.
> Better handling of HdlInterfaceServer crashes

- HdlInterfaceService.py
- compiler/src/main/scala/edg/compiler/CompilerServerMain.scala
- compiler/src/main/scala/edg/compiler/PythonInterface.scala
- compiler/src/main/scala/edg/util/QueueStream.scala
- compiler/src/main/scala/edg/util/StreamUtils.scala
- compiler/src/test/scala/edg/compiler/PythonInterfaceTest.scala
- edg_core/BufferSerializer.py
- edg_core/ScalaCompilerInterface.py
- edg_core/test_bufferserializer.py
Since communication between Python <-> Scala uses stdio (stdin and stdout), previously any stray print()s in user HDL would mess up that communication. This adds a non-ASCII magic header byte (0xfe) to the communication stream that is used to indicate the start of a proto message, the rest is interpreted as stdout prints.
As typical since this is purely a UI and quality-of-life change without modifying core semantics, I'm going to go ahead and merge this when ready. Post-merge feedback is still welcome.
This solution definitely has problems and should be replaced, see #131 
Implementation notes:
- buffering is pretty bad, the HdlInterfaceServer must be launched with -u otherwise it buffers excessively
- print() seems to buffer separately from sys.stdout.buffer
- currently the println …
> Support print() in user HDL

- electronics_lib/Microcontroller_Esp32c3.py
- electronics_lib/UsbPorts.py
- electronics_lib/__init__.py
- examples/test_blinky.py
- examples/test_can_adapter.py
- examples/test_debugger.py
- examples/test_ledmatrix.py
- examples/test_multimeter.py
- examples/test_tofarray.py
- examples/test_usb_source_measure.py
Resolves #121, resolves #123 
Changes the Type-C receptacle to automatically generate the CC pull resistors when CC not externally connected and power is used. Removes the Type-C Device Connector block which included the CC pull resistors but did not give a CC port option - this one unifies both in one smart block. Also grounds the shield pin, but this can be revisited with more options in the future since there doesn't seem to be wide agreement on what should be done with this pin.
Also adds a programming button to the ESP32-C3 module. In the future (when there's a use case) this may be disable-able by a user toggle or something.
Largely a hardware change based on lessons learned from the LED matrix board. Review not gating since core models do not change but feedback is welcome.
> Automatically generate USB-C CC pull resistors, add programming button to ESP32-C3

- compiler/src/main/scala/edg/util/MapUtils.scala
- compiler/src/main/scala/edg/wir/Refinements.scala
- compiler/src/test/scala/edg/compiler/CompilerRefinementTest.scala
- compiler/src/test/scala/edg/wir/RefinementsTest.scala
Needed for ongoing IDE work, to support stacking refinements on top of other refinements.
Also moves mergeMapSafe from the IDE into compiler.
Not a model or significant user-facing change, will be merged when automated tests pass.
> Support ++ on refinements

- edg/BoardTop.py
- electronics_lib/JlcPart.py
- examples/test_ledmatrix.py
- examples/test_multimeter.py
- examples/test_tofarray.py
- examples/test_usb_source_measure.py
One of those rare PRs with much more deletions than additions!
This changes the JLC parts to not require basic parts by default, since in most cases there is not going to be a basic part available and just results in a lot of boilerplate code. The only exceptions are the RCs where this check might be meaningful. Users can also override this to be true to get errors for all non-basic parts.
> Clean up require_basic_part

- compiler/src/main/scala/edg/compiler/Compiler.scala
- compiler/src/test/scala/edg/compiler/CompilerRefinementTest.scala
Perhaps not the cleanest implementation, but this suppresses class refinements when they both target the same parameter.
As a minor bugfix (instead of intentional semantics change) that a current design is dependent on I'm going to merge this when tests pass.
> Instance refinements take priority over class refinements

- compiler/src/main/scala/edg/compiler/Compiler.scala
- compiler/src/main/scala/edg/compiler/CompilerError.scala
- compiler/src/main/scala/edg/compiler/CompilerServerMain.scala
- compiler/src/main/scala/edg/compiler/DesignAssertionCheck.scala
- compiler/src/test/scala/edg/CompilerTestUtil.scala
- compiler/src/test/scala/edg/compiler/CompilerEvaluationTest.scala
- edg_core/ScalaCompilerInterface.py
- edg_core/test_assertion.py
Changes assertion checking to be done by a separate transform, instead of interleaved with the main compiler. This also removes the assertion state from the compiler, which was redundant in any case with the final design.
Adds unit tests to check assertion behavior, both in the failed and missing cases.
This shouldn't change any behavior or interfaces, this is purely an implementation detail refactoring.
> Assertion refactor

- compiler/src/main/scala/edg/compiler/Compiler.scala
- edg_core/ConstraintExpr.py
As the title says, removes RewriteArrayAllocate, by flattening it into when the link array port is processed since it has no dependencies.
Something similar is done for link ports, but we still RewriteConnectAllocate since block-side port arrays have dependencies.
Also fixes a type annotation that errors on recent versions of mypy.
This is an implementation change and should not affect semantics.
> Remove RewriteArrayAllocate compiler step

- edg/BoardCompiler.py
... previously if run as `__main__` the output gets stuffed in a `__main__` directory. This is bad for running blinky_skeleton from the command line.
This should not affect the behavior of existing unit tests, it only fixes the behavior when running as `__main__`.
> User name of file for output directory of compiling boards

- .github/workflows/pr-scala.yml
otherwise those fail with a missing Python dependency error.
> Add new dependencies to Scala PR automated tests

- getting-started.md
Add error message examples and resolutions for Python-dependencies-not-found and submodule-not-cloned
> Address common errors from the tutorial

- compiler/src/test/scala/edg/compiler/PythonInterfaceTest.scala
Makes the unit test not red when run from the edg-ide project.
> Use project-independent path for PythonInterfaceTest

- compiler/src/main/scala/edg/compiler/Compiler.scala
- compiler/src/main/scala/edg/compiler/CompilerError.scala
- compiler/src/main/scala/edg/compiler/ConstProp.scala
Additionally fixes:
- False-positive late forced-set when a forced value and lower priority assign have the same target expr - fixed by recording and checking the constraint name.
- Unintentional order-sensitivity in comparison of link-array elements and connected port array elements.
- Updates the JAR from #170
> Compiler edge case fixes

- README.md
- compiler/src/main/scala/edg/compiler/PythonInterface.scala
- getting-started.md
- catches and stores errors if the Python subprocess fails to start, so errors can be reported through the normal flow instead of just crashing immediately - in particular for unit tests, this means the error message is reported, instead of directly printed and immediately clobbered by the test failure spam that doesn't include useful diagnostics
- add Deprecated pip package to README
- update the submodule not cloned error to use the new sub-project name
- add python-is-python3 issue and solution for Linux
- suggest debugging with just one test instead of all of them
- suggest JRE/JDK versions
- runs natively on major OSes
> Improve setup documentation and debuggability

- HdlInterfaceService.py
- compiler/src/main/scala/edg/compiler/PythonInterface.scala
- examples/test_blinky.py
Prior, when refdesing an empty design, it returns an empty proto because the message type doesn't get set. This adds an explicit SetInParent.
For error output: this removes the "while running ...", pushing that onto the upper level UI.
> Fix bug with refdesing empty design; deduplicate error output

- .gitignore
Since we now have generated .pdf files, they probably shouldn't be committed just like the generated .net (and other) files.
> gitignore generated PDF files

- electronics_abstract_parts/AbstractCapacitor.py
- electronics_abstract_parts/AbstractResistor.py
- electronics_abstract_parts/test_kicad_part_parsing.py
- electronics_model/PartParserUtil.py
- electronics_model/test_part_parser.py
eg, '4k7' - in the underlying parsing infrastructure that supports both the parts table and kicad import
> Support inline SI prefix notation

- compiler/src/main/scala/edg/compiler/Compiler.scala
- electronics_abstract_parts/IoController.py
- electronics_lib/Microcontroller_Esp32.py
- electronics_lib/Microcontroller_Esp32c3.py
- electronics_lib/Microcontroller_Lpc1549.py
- electronics_lib/Microcontroller_Stm32f103.py
- electronics_lib/Microcontroller_nRF52840.py
... so the IoController subclass list is clean for application-level subcircuits instead of bare chips
Also changes the compiler so that bad array references will not lower (and cause an error in structural validation) instead of crashing the compiler
> Refactor internal microcontrollers to use BaseIoController

- edg_core/Generator.py
- electronics_abstract_parts/AbstractCapacitor.py
- examples/test_bldc.py
General rule of thumb for ceramic capacitors is to specify a voltage rating of twice the operating voltage. This adds that functionality.
This doesn't change the current hacktastic capacitance derating (where if the capacitor is operating under high voltage, more nameplate capacitance is requested to offset capacitance derating).
In practice this doesn't have seemed to changed any of the part selections, perhaps because the default capacitors are already pretty high voltage.
Also adds a note about why generators only take arg-params.
> Capacitor voltage-rating derating

- electronics_abstract_parts/AbstractDiodes.py
Prior, it was using the spec limits which are loose (wider) than the limits of the actual selected part. This allows voltage_limits to more accurately reflect actual limits.
> Set Zener protection voltage limits to reflect actual limits

- compiler/src/main/scala/edg/compiler/Compiler.scala
- compiler/src/main/scala/edg/compiler/ConstProp.scala
- compiler/src/main/scala/edg/wir/DesignPath.scala
- compiler/src/test/scala/edg/compiler/ConstPropTypeTest.scala
- requirements.txt
For IDE changes.
- Add Compiler.getParamType to inspect parameter types
- Change ConstProp paramTypes to use IndirectDesignPath, to support things like names (not currently implemented)
- Change IndirectStep to case objects, to allow serialization
- Pin sexpdata dependency to version 0.0.3, since 0.0.4 is API-incompatible
> Internal API changes

- HdlInterfaceService.py
- electronics_abstract_parts/AbstractDevices.py
- electronics_abstract_parts/AbstractDiodes.py
- electronics_abstract_parts/AbstractFuse.py
- electronics_abstract_parts/AbstractJumper.py
- electronics_abstract_parts/AbstractOpamp.py
- electronics_abstract_parts/AbstractResistor.py
- electronics_abstract_parts/AbstractSwitch.py
- electronics_abstract_parts/AbstractTestPoint.py
- electronics_abstract_parts/Categories.py
- electronics_abstract_parts/I2cPullup.py
- electronics_abstract_parts/OpampCircuits.py
- electronics_abstract_parts/PassiveFilters.py
- electronics_abstract_parts/ResistiveDivider.py
- electronics_abstract_parts/UsbBitBang.py
- electronics_abstract_parts/UsbConnectors.py
- electronics_abstract_parts/__init__.py
- electronics_lib/PassiveConnector.py
- electronics_lib/PowerConnectors.py
- electronics_lib/Speakers.py
- electronics_model/ConnectedGenerator.py
Adds a few more categories, focusing on what a system designer might look for in terms of categories instead of implementation details. In particular moves a lot of DiscreteApplication into functional categories (eg, protection, analog).
Also don't index DesignTop, since it both clutters the library panel and causes an IDE check to fail.
> More categories cleanup

- compiler/src/main/scala/edg/compiler/Compiler.scala
- compiler/src/main/scala/edg/compiler/ConstProp.scala
- compiler/src/main/scala/edg/compiler/PythonInterface.scala
- compiler/src/main/scala/edg/util/DependencyGraph.scala
- compiler/src/main/scala/edg/wir/BlockLike.scala
- compiler/src/main/scala/edg/wir/DesignPath.scala
- compiler/src/main/scala/edg/wir/Library.scala
- compiler/src/main/scala/edg/wir/Refinements.scala
- compiler/src/test/scala/edg/compiler/CompilerPartialBlockTest.scala
- compiler/src/test/scala/edg/compiler/CompilerPartialParamTest.scala
- compiler/src/test/scala/edg/compiler/CompilerPartialTest.scala
- compiler/src/test/scala/edg/compiler/CompilerRefinementTest.scala
- compiler/src/test/scala/edg/compiler/ConstPropAssignTest.scala
- compiler/src/test/scala/edg/util/DependencyGraphTest.scala
- compiler/src/test/scala/edg/wir/RefinementsTest.scala
Prior, partial compilation (prevent the compiler from compiling certain items) only supported blocks-by-path and params-by-path. This adds support for blocks-by-class and params-by-class-value (some internal parameter of all blocks of a class, eg, Resistor:resistance).
The one edge case here is that when additional refinements are added, it may need to re-visit previously elaborated classes to apply new class-value refinements. That is done now on `fork`, along with a check on new class-based subclass refinements.
Infrastructure changes
- Refactors partial compilation to happen solely in the Compiler, holding back ElaborateRecord
- Prior, this was a bit of a mess, also having some specialized logic in ConstProp
- Overall the frozen handling style is much more unified and consistent
- …
> Class-value partial compilation

- edg/BoardTop.py
- electronics_lib/Fpga_Ice40up.py
- electronics_lib/Microcontroller_Esp32.py
- electronics_lib/Microcontroller_Lpc1549.py
- electronics_lib/Microcontroller_Rp2040.py
- electronics_lib/Microcontroller_Stm32f103.py
- electronics_lib/Microcontroller_Stm32f303.py
- electronics_lib/Microcontroller_nRF52840.py
- electronics_lib/Neopixel.py
- electronics_model/BomBackend.py
- examples/jlcpcb_pcba_postprocess.py
- When doing pin allocation, allocate the DAC first, then the ADC, since those are probably the most restrictive
- Add default implementation for abstract Neopixel, to the classic WS2812b
- BoM generation: use Package as column header, JLC seems to no longer accept Footprint
- Add default speaker implementation (to the connector-speaker)
- Add more corrections to the position postprocess script
> Parts cleanup

- .github/workflows/pr-python.yml
- developing.md
- edg_core/Core.py
- edg_core/Util.py
- examples/test_blinky.py
- pyproject.toml
Add local packaging run to workflow tests, with an abbreviated (blinky-only) unittest and top-level test.
Resolves #251, where blocks defined in `__main__` cause an error when the HDL server tries to resolve those blocks, because the HDL server is a separate Python instance and thinks itself is `__main__` (instead of the original file). The fix is to detect when a library's module is `__main__` and effectively guess the correct original module name by using the filename. Might be a better way to do it, but this works, and is largely what a websearch turned out for finding the original module name for `__main__`.
Bumps the package version since this is a significant bugfix.
> Add packaging tests, support blocks defined in __main__

- edg_core/Core.py
- edg_hdl_server/__main__.py
Also adds an assertion guard in case a non_library element tries to elaborate, the overall idea is that non_library parts behave as if they don't exist from a compilation standpoint
> Don't include non_library parts in superclasses

- electronics_abstract_parts/AbstractLedDriver.py
- electronics_abstract_parts/IdealIoController.py
- electronics_abstract_parts/IoController.py
- electronics_abstract_parts/IoControllerInterfaceMixins.py
- electronics_abstract_parts/__init__.py
- electronics_lib/LedDriver_Al8861.py
- electronics_lib/Microcontroller_Esp.py
- electronics_lib/Microcontroller_Esp32.py
- electronics_lib/Microcontroller_Esp32s3.py
- electronics_lib/Microcontroller_Lpc1549.py
- electronics_lib/Microcontroller_Rp2040.py
- electronics_lib/Microcontroller_Stm32f103.py
- electronics_lib/Microcontroller_Stm32f303.py
- electronics_lib/Microcontroller_nRF52840.py
- electronics_lib/__init__.py
- examples/test_can_adapter.py
- examples/test_datalogger.py
- examples/test_fcml.py
- examples/test_high_switch.py
- examples/test_iot_display.py
- examples/test_iot_fan.py
- examples/test_iot_knob.py
- examples/test_iot_led_driver.py
- examples/test_robotcrawler.py
- examples/test_robotdriver.py
- examples/test_seven_segment.py
- examples/test_simon.py
- examples/test_swd_debugger.py
- examples/test_tofarray.py
- examples/test_usb_source_measure.py
- Create abstract LedDriver class, refactor Al8861 to inherit this and its mixins
- Break out USB, CAN, DAC from abstract IoController
- IdealIoController now implements I2S (in addition to the other mixins)
- Refactor ESP auto-programming header to be a mixin
> Continue refactoring to use mixins

- compiler/src/main/scala/edg/compiler/Compiler.scala
- compiler/src/test/scala/edg/compiler/CompilerRefinementTest.scala
- examples/test_robotowl.py
- examples/test_switch_controller.py
- examples/test_usb_uart.py
Class refinements and block-based default can now chain, eg PassiveHeader -> PinConnector254 and PinConnector254 -> PinConnector254Vertical will result in PassiveHeader -> PinConnector254Vertical.
> Recursively resolve refinements

- edg_core/Blocks.py
- edg_core/Builder.py
- edg_core/HierarchyBlock.py
- edg_core/IdentityDict.py
- edg_core/Link.py
- edg_core/test_block_errors.py
- edg_core/test_hierarchy_block.py
- edg_core/test_port_adapter.py
- Make connects operations incremental again, that is validation happens on every `connect(...)` and errors should show the failing line
- Connects treat the first port as authoritative in determining the link type
- Implement net joins, by merging ports of other connects into the first connect and maintaining a delegation graph;
- Surprisingly this wasn't too difficult
- Remove adapter naming component of skipped test
- Add debugging into to exceptions (by rethrowing) in Builder elaboration
- Fix infrastructural bug in IdentityDict, where `setdefault` failed to set `keys_dict`
- Add `__bool__` for IdentityDict
> Connect refactor: incremental connect, support connect joins

- electronics_abstract_parts/IoController.py
- examples/test_can_adapter.py
- examples/test_datalogger.py
Legacy code had CAN and USB on all IoControllers, but mixins changed that (because USB and CAN are not universal peripherals) which was a breaking change. This automatically materializes the USB and CAN mixins when requested using legacy-style code, by overloading `__getattr__(...)`. This should also correctly encode the requirement for mixins as part of the block type.
Likely examples and tutorials will continue using the old-style (non-mixin) USB syntax for simplicity.
> Automatically materialize USB and CAN mixins for compatibility

- compiler/src/main/scala/edg/EdgirUtils.scala
- compiler/src/main/scala/edg/ElemBuilder.scala
- compiler/src/main/scala/edg/compiler/Compiler.scala
- compiler/src/main/scala/edg/wir/BlockLike.scala
- compiler/src/main/scala/edg/wir/LinkLike.scala
- compiler/src/main/scala/edg/wir/Mixins.scala
- compiler/src/main/scala/edg/wir/PortLike.scala
- compiler/src/test/scala/edg/EdgirUtilsTest.scala
- compiler/src/test/scala/edg/compiler/CompilerBlockMixinTest.scala
- compiler/src/test/scala/edg/compiler/CompilerRefinementTest.scala
... in the metadata field for now, structure is non-API-stable.
Infrastructure used to pass this data to the block diagram visualizer, which should render non-interactable ports differently.
Add utility functions for working with metadata:
- Seq[String] to metadata and inverse operation
- Insertion and retrieving fields from metadata, if structured as members.node
- Merge metadata - valid for dict only, only performs merges one level deep
> Store post-refinement-only params and ports in design

- electronics_abstract_parts/AbstractPowerConverters.py
- electronics_abstract_parts/DigitalAmplifiers.py
- electronics_abstract_parts/IoController.py
- electronics_abstract_parts/SmdStandardPackage.py
- electronics_lib/BoostConverter_TexasInstruments.py
- electronics_lib/FanConnector.py
- electronics_lib/Microcontroller_Lpc1549.py
- electronics_lib/Microcontroller_Stm32f303.py
- electronics_lib/Microcontroller_nRF52840.py
Add non_library tags (to prevent some items from showing up in the library browser) and categorization superclasses.
Also add a output-voltage-greater-than-input constraint to the Tps61040 boost converter.
> Cleanup type hierarchy / categorization

- electronics_abstract_parts/IdealIoController.py
- electronics_abstract_parts/IoController.py
- electronics_abstract_parts/IoControllerInterfaceMixins.py
- electronics_abstract_parts/__init__.py
- electronics_lib/Microcontroller_Esp32.py
- electronics_lib/Microcontroller_Esp32c3.py
- electronics_lib/Microcontroller_Esp32s3.py
- electronics_lib/Microcontroller_Lpc1549.py
- electronics_lib/Microcontroller_Rp2040.py
- electronics_lib/Microcontroller_Stm32f103.py
- electronics_lib/Microcontroller_Stm32f303.py
- electronics_lib/Microcontroller_nRF52840.py
- examples/test_robotcrawler.py
Although these are supported almost universally, these are much less commonly used and add visual clutter in the IDE block diagram, especially in connect mode where they are an available connect like their controller port counterparts.
> Move I2cTarget and SpiPeripheral outside base IoController

- electronics_lib/Microcontroller_Esp32.py
- electronics_lib/Microcontroller_Esp32c3.py
- electronics_lib/Microcontroller_Esp32s3.py
- electronics_lib/Microcontroller_nRF52840.py
Removes IoController from supertypes of internal chip blocks.
Also fixes one of the nRF52840 module that was missing a generate super call.
> Clean up microcontrollers

- edg/BoardTop.py
- electronics_abstract_parts/IoController.py
- electronics_abstract_parts/IoControllerInterfaceMixins.py
- examples/test_fcml.py
- examples/test_iot_display.py
- examples/test_iot_knob.py
- examples/test_swd_debugger.py
- examples/test_tofarray.py
- examples/test_usb_source_measure.py
- SimpleBoardTop now uses the JLC base with simplifying refinements
- USB moved back into IoController (base), since mixins do not (yet) have GUI support, and USB device mode is probably a common enough applicatiion
> Minor usability improvements

- .github/workflows/pr-scala.yml
- compiler/src/main/scala/edg/compiler/Compiler.scala
- compiler/src/main/scala/edg/compiler/ExprEvaluate.scala
- edg_core/Binding.py
- edg_core/ConstraintExpr.py
- edg_hdl_server/__main__.py
- electronics_abstract_parts/AbstractTestPoint.py
- examples/BldcController/BldcController.net
- examples/IotKnob/IotKnob.net
- examples/RobotCrawler/RobotCrawler.net
- examples/RobotDriver/RobotDriver.net
- examples/RobotDriver3/RobotDriver3.net
- examples/SevenSegment/SevenSegment.net
- examples/TofArray/TofArray.net
Add + operator to StringExpr, including compiler support and a versioning bump.
Allow optional specification of test point names. If unspecified, it defaults to the link name.
Also update CI definition to avoid a flakey test
> String add ops, optional test point naming

- electronics_abstract_parts/AbstractPowerConverters.py
- electronics_abstract_parts/IoController.py
- electronics_lib/LinearRegulators.py
- electronics_lib/Microcontroller_Esp32c3.py
- electronics_lib/SwitchMatrix.py
- electronics_lib/__init__.py
Add the XIAO ESP32C3 microcontroller dev board (power input and output modes). Untested. Note, since the ESP32C3 has a lot of pins needed for boot, only 6 of the 11 IO pins end up usable.
Improves the docstring for these classes:
- Abstract IoController
- Abstract VoltageRegulator
- Abstract LinearRegulator
- Ldl1117
- SwitchMatrix
> Add XIAO ESP32C3, prototype docstring improvement for some devices

- edg_core/Blocks.py
- edg_core/HierarchyBlock.py
Adds an optional `doc='...'` argument to `self.Port(...)`, `self.Parameter(...)` and `self.ArgParameter(...)`. Docs are stored in the block, similar to how optional and port tags are tracked. The idea is this keeps documentation close to the port definition and (in the future) allows tools that are port-/parameter-aware to generate documentation specific to the data model here.
Python doesn't have a accepted convention for class attribute docs, so we're going to make our own. [PEP 224](https://peps.python.org/pep-0224/) was a proposal for attribute docstrings, but was rejected.
Quick informal conventions:
- Type information should not be repeated in the docstring.
- Other arguments to Port should not be repeated in the docstring (e.g., optional, port tags). Tools should automatically add …
> Experimental API for port and param docs

- electronics_lib/LedMatrix.py
- electronics_lib/Neopixel.py
- electronics_lib/SwitchMatrix.py
- examples/BasicKeyboard/BasicKeyboard.svgpcb.js
- examples/IotKnob/IotKnob.svgpcb.js
- examples/Keyboard/Keyboard.svgpcb.js
- examples/LedMatrix/LedMatrix.svgpcb.js
Makes the ID consistent with the netlist name generation.
> SVGPCB templates name fix

- compiler/src/main/scala/edg/compiler/Compiler.scala
- compiler/src/main/scala/edg/compiler/CompilerError.scala
- compiler/src/test/scala/edg/compiler/CompilerPartialBlockTest.scala
Adds an optional progressFn to Compiler, which is regularly called and updated with the overall compilation progress.
Each block has some progress value, defined as the total compilation progress (0-1) completed when the block and its subtree are fully compiled. The top block's progress value is 1, and each block's progress is the parent's progress divided by the immediate number of siblings plus 1 (the extra 1 is for the parent itself - updated when the block is compiled).
In practice this isn't linear, since units of work get progressively smaller, but it's probably better than nothing.
> Compile progress

- edg/core/Array.py
- edg/core/Blocks.py
- edg/core/Core.py
Prior, exceptions that use _name_of that had an unknown element would stack-trace with the _name_of. This could happen, for instance, during an invalid implicit connect before the Block is assigned a name. This adds an optional argument to _name_of to auto-generate unknown names for elements.
The generate unknown names behavior isn't default for cases where the name must be valid (as opposed to only being helpfully informative).
> Allow unnamed elements in error messages

- .gitignore
- edg/core/Range.py
- edg/parts/JlcCapacitor.py
some mini improvement when debug the the capacitor generator:
I found most 47uF capacitor is in big smt size 1210 that is current ignored in JlcCapacitor.py csv part loader.
- fix Range.fuzzy_in() typo bug and add 1210 capacitor smt size
> fix Range.fuzzy_in() typo bug and add 1210 capacitor smt size

- edg/core/Blocks.py
- edg/core/test_bundle.py
- edg/core/test_connect_bundle.py
Adds a frontend error so it doesn't result in a confusing compiler internal error.
Also fixes an unrelated type annotation issue flagged by a new version of mypy.
> Disallow inner connects

- edg/abstract_parts/AbstractCapacitor.py
- edg/abstract_parts/AbstractLed.py
- edg/abstract_parts/AbstractOpamp.py
- edg/abstract_parts/AbstractResistorArray.py
- edg/abstract_parts/Categories.py
- edg/abstract_parts/UsbBitBang.py
- edg/abstract_parts/__init__.py
- edg/core/Generator.py
- edg/parts/EnvironmentalSensor_Bme680.py
- edg/parts/EnvironmentalSensor_Sensirion.py
- edg/parts/EnvironmentalSensor_Ti.py
- edg/parts/IoExpander_Pca9554.py
- edg/parts/IoExpander_Pcf8574.py
- edg/parts/Microphone_Sd18ob261.py
- edg/parts/SpeakerDriver_Analog.py
- edg/parts/SpeakerDriver_Max98357a.py
Resolves #312 
- Add subcategorizations of Interface and EnvironmentalSensor
- Add MultipackDevice categorization, which replaces any prior categorization - multipack devices should not be used in the context of a normal block
> improve categorization

- compiler/src/main/scala/edg/compiler/Compiler.scala
- compiler/src/main/scala/edg/compiler/CompilerServerMain.scala
- compiler/src/main/scala/edg/compiler/PythonInterface.scala
- compiler/src/main/scala/edg/util/QueueStream.scala
- compiler/src/test/scala/edg/compiler/PythonInterfaceTest.scala
- edg/core/ScalaCompilerInterface.py
- edg/core/test_generator.py
- edg/hdl_server/__main__.py
... instead of spawning a sub-process. This keeps namespaces consistent (in a way that spawning a subprocess wouldn't) and allows the use of a Python debugger. Resolves #362 
NOTE FOR DEBUGGING: the IDE (compile-design) does not yet support debugging, so you'll need to create a main stub (like bllinky_skeleton.py, as if running from the command line) and debug from that. But breakpoints do work.
Implementation-wise, this 'flips' the client / server role: after sending the design to compile to the server, the Python process then acts as an HDL server until receiving an empty request (denoting end of compilation), then waits for the compilation result. This also restructures the interface structure, notably bringing the core compiler interface structurally closer to the Python …
> Re-use host Python process when compiling from command line

- edg/parts/PassiveConnector_Fpc.py
This should cover most of the popular P0.5 fpc sizes. FCC and FCA are just different packages.
> Add: FPC 0.5mm pitch top and bottom connector JLC parts numbers

- edg/parts/Ina219.py
- edg/parts/__init__.py
> Add: Ina219 current/voltage sensor over I2C

- edg/electronics_model/KiCadSchematicBlock.py
- edg/electronics_model/resources/test_kicad_import_inline.kicad_sch
- edg/electronics_model/resources/test_kicad_import_inline_badmultiline.kicad_sch
- edg/electronics_model/test_kicad_import.py
- getting_started_schimport.md
Hacked in by concatenating Value2, Value3, ... fields if they exist. Fields must start at Value2 and be contiguous. This should allow better-looking schematic-defined blocks with more complex logic.
> Schematic import multiline value support

- edg/abstract_parts/AbstractDevices.py
- edg/abstract_parts/AbstractResistor.py
- edg/abstract_parts/IoControllerInterfaceMixins.py
- edg/abstract_parts/PassiveFilters.py
- edg/abstract_parts/__init__.py
- edg/electronics_model/CircuitBlock.py
- edg/electronics_model/DigitalPorts.py
- edg/electronics_model/GroundPort.py
- edg/parts/Batteries.py
- edg/parts/Microcontroller_Rp2040.py
- edg/parts/PowerConditioning.py
- edg/parts/__init__.py
- examples/test_blinky.py
- examples/test_multimeter.py
Add an example with a Xiao RP2040 powered from a 4x stack of AA batteries.
Library changes:
- Add IoControllerVin, for microcontroller dev boards with a >=5v Vusb in / Vin pin
- Add link type to Ground port and fix up some places that were still using VoltageLink
- Make the link type covariant, so Port[GroundLink] and Port[VoltageLink] are both Port[Any]
- Add AaBatteryStack for a series stack of AA batteries that boost the voltage
- Change battery model to support offset ground for series stacks. A one-of change for now, in the future most robust / consistent support for offset ground is needed.
- Change AA battery limits to 1.0-1.6v to accommodate NiMH rechargeable cells. 1.0v lower limit is a compromise to get the Xiao to build, devices may want to support down to 0.9v to maximize …
> Add AA battery stack to library and Vin to Xiao RP2040

- compiler/src/main/scala/edg/compiler/ExprEvaluate.scala
- edg/core/ConstraintExpr.py
- edg/parts/Batteries.py
Ints can be 'promoted' to floats and ranges and used in their operations. Change int invert semantics to promote to float, consistent with Python behavior.
> Improve int handling

- compiler/src/main/scala/edg/compiler/Compiler.scala
- compiler/src/main/scala/edg/compiler/CompilerError.scala
- compiler/src/main/scala/edg/compiler/ConstProp.scala
- compiler/src/main/scala/edg/util/DependencyGraph.scala
- compiler/src/test/scala/edg/compiler/CompilerPartialBlockTest.scala
- compiler/src/test/scala/edg/util/DependencyGraphTest.scala
... SMU example compile time (core compile time only, with hot cache including generator results) goes from ~minute to a bit under a second.
Fixes two major performance bugs:
- ConstProp used prevent parameters without types declared from propagating by rejecting it from the ready queue, repeatedly. This now adds the parameter declaration as a dependency.
- (probably) DependencyGraph used to subtract the entire values keySet, which would get massive, this now does a filterInPlace on incoming dependencies which should be much smaller
Also changes a few things from Set to Iterable, which may marginally improve performance
> Core compiler optimization: fix MASSIVE performance bugs

- edg/parts/Rf_Sx1262.py
https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/RQ000008nKCH/hp2iKwMDKWl34g1D3LBf_zC7TGBRIo2ff5LMnS8r19s
This pull request includes a single change to the `contents` method in the `Rf_Sx1262.py` file. The crystal frequency was updated to align with data sheet.
* **Crystal frequency update**:
- Changed the crystal frequency from `30 MHz` to `32 MHz` for the `Rf_Sx1262` component to align with the ref design
> Fix: replace the crystal to 32MHz according to the ref design
