- compiler/build.sbt
- compiler/src/main/scala/edg/compiler/Compiler.scala
- compiler/src/main/scala/edg/compiler/ConstProp.scala
- compiler/src/main/scala/edg/compiler/ExprValue.scala
- compiler/src/main/scala/edg/util/DependencyGraph.scala
- compiler/src/main/scala/edg/wir/BlockConnectivityAnalysis.scala
- compiler/src/main/scala/edg/wir/BlockLike.scala
- compiler/src/main/scala/edg/wir/LibraryConnectivityAnalysis.scala
- compiler/src/main/scala/edg/wir/Mixins.scala
- compiler/src/main/scala/edg/wir/Refinements.scala
- compiler/src/test/scala/edg/compiler/CompilerExpansionTest.scala
DO NOT MERGE - DEPENDS ON #40 
... and add deprecations to the compiler options
> Clean up deprecations

- .gitignore
- Pipfile
... so pipenv can auto-fetch dependencies ...
> Add pipfile

- compiler/src/main/scala/edg/compiler/PythonInterface.scala
Fix for #126 since that would have just eaten any stderr output.
> Propagate stderr from Python interface

- .github/workflows/pr-python.yml
- .github/workflows/pr-scala.yml
- examples/test_ledmatrix.py
also make CI Java version consistent with new IDE CI configuration
> Expand CI to run some examples

- compiler/project/build.properties
- compiler/project/plugins.sbt
An outdated version of protoc seems to not be happy with ARM Macs
> Bump dependency versions

- edg_core/Core.py
- electronics_abstract_parts/PinMappable.py
Otherwise things die on Python 3.8 and below it seems...
> Fix type error, improve booling error message

- electronics_lib/Microcontroller_Esp.py
- electronics_lib/Microcontroller_Esp32.py
- electronics_lib/Microcontroller_Esp32c3.py
- electronics_lib/__init__.py
- electronics_model/AnalogPort.py
Just the library block, tested to netlist by hack-patching the LED matrix. This will be used in a robot driver variant soon.
> ESP32-WROOM-32 microcontroller

- compiler/src/main/scala/edg/compiler/CompilerServerMain.scala
... otherwise the compiler freezes, possibly because some IPC queue got full.
> Incrementally forward compiler outputs

- edg_core/Array.py
- electronics_abstract_parts/ESeriesUtil.py
- electronics_model/NetlistGenerator.py
Looks like an updated version of mypy catches more stuff
> Fix mypy type errors

- .github/workflows/pr-python.yml
- compiler/src/main/scala/edg/wir/Refinements.scala
- compiler/src/test/scala/edg/wir/RefinementsTest.scala
Add an utility method
Also fixes dependencies for mypy proto
> Refinements.toPb

- HdlInterfaceService.py
Looks like this was accidentally'd in a bad merge in #178
> Restore refdesing option in HDL

- compiler/src/main/scala/edg/compiler/Compiler.scala
Refactoring for the IDE, to clean up some of the code there
> Make some immutable Compiler values accessible

- compiler/src/main/scala/edg/compiler/CompilerError.scala
- compiler/src/main/scala/edg/compiler/DesignAssertionCheck.scala
+ added compiler argument through assertion functions
> piped compiler through assertions

- edg_core/Blocks.py
Eventually we need to implement net joins, and probably also refactor the connect algorithm to be incremental again. But this is a quick stopgap.
> A more useful TODO implement net join error

- electronics_abstract_parts/AbstractPowerConverters.py
IdealBuckBoost fixed to output the spec voltage, instead of the input voltage 🙃
Change the tolerancing to be full range
> Fix ideal DC-DC converters

- compiler/src/main/scala/edg/compiler/Compiler.scala
- compiler/src/main/scala/edg/compiler/ConstProp.scala
- compiler/src/main/scala/edg/wir/Refinements.scala
- compiler/src/test/scala/edg/compiler/CompilerRefinementTest.scala
- compiler/src/test/scala/edg/compiler/ConstPropAssignTest.scala
- compiler/src/test/scala/edg/wir/RefinementsTest.scala
- edg_core/Refinements.py
- edg_core/__init__.py
- edgrpc/hdl_pb2.py
- edgrpc/hdl_pb2.pyi
- examples/test_bldc.py
- examples/test_fcml.py
- examples/test_high_switch.py
- examples/test_multimeter.py
- examples/test_simon.py
- proto/edgrpc/hdl.proto
Refinements can now be a ParamValue of another parameter, instead of only explicit values. This allows some deduplication and allowing a single value to drive multiple parameters, useful for multi-channel designs.
> Directed refinement

- MANIFEST.in
> PEP 561 typed package

- electronics_abstract_parts/IoController.py
> Current draw propagation for IdealIoController

- electronics_abstract_parts/IoControllerInterfaceMixins.py
- electronics_lib/SwitchMatrix.py
- Fix ncols for switch matrix
- Allocate USB pins first, since they're generally dedicated pins
> Small fixes

- electronics_lib/LightSensor_As7341.py
- electronics_lib/__init__.py
- electronics_model/DigitalPorts.py
Also adds output threshold abs to DigitalBidir.from_supply, to emulate the I2C pulldown
> AS7341 spectral light sensor

- compiler/src/main/scala/edg/compiler/Compiler.scala
- compiler/src/main/scala/edg/compiler/CompilerServerMain.scala
- compiler/src/main/scala/edg/compiler/PythonInterface.scala
- edg_hdl_server/__main__.py
Adds a log warning if the proto version looks incompatible.
Also update the proto version to 2.
> Check proto version

- compiler/src/main/scala/edg/wir/DesignPath.scala
... which returns the postfix as a Seq[String], a format used in the IDE
> Add DesignPath.refFromOption

- compiler/src/main/scala/edg/compiler/ExprValue.scala
> Add ExprValue.classFromValInit

- edg_core/HierarchyBlock.py
This allows inspect to work on methods decorated with `@init_in_parent`
> @wraps init_in_parent

- compiler/src/main/scala/edg/compiler/PythonInterface.scala
... to allow it to be terminated anytime
> Add PythonInterface.destroy

- compiler/build.sbt
- compiler/project/build.properties
> Bump to Scala 2.13.14, sbt 1.9.9

- edg/parts/JlcResistor.py
Do we still need to merge this?
> Update: handling zero voltage rating cases
